### ISSUE TITLE
Update attempt throws an error

### ISSUE THREAD

**Issue by apoapostolov** [LyncsCwtsh/fvtt-module-nice-more-dice#1]
![image](https://user-images.githubusercontent.com/4083812/125207800-15e1f100-e297-11eb-9697-9de99de0e5d5.png)

**Comment by LyncsCwtsh** [comment]
fixed, sorry about that^^ first module, silly mistake - if you redownload it, there shouldn't be an annoying error anymore (I'll figure out how releases and such work in the future)
