### ISSUE TITLE
Texture files cannot be found

### ISSUE THREAD

**Issue by Bryn1701** [LyncsCwtsh/fvtt-module-nice-more-dice#2]
When trying to use this new interesting module, I kept getting errors, none of the textures seemed to be found. Then I saw that the folders and files do not match. Some are capitals and some are not, and I believe is the issue of the mismatch.

**Comment by LyncsCwtsh** [comment]
You are correct, some capitalization issues I didn't catch since I am self hosting on windows. Corrected the script, so it should work now (just reinstall the module for now, I'll figure out how to do releases properly in the future). Thanks for the report!
Leaving this issue open for now, since I can't check if I caught all necessary name differences.

**Comment by subatoiWolf** [comment]
Throwing errors and cant get the textures to show at all on Forge.  Looks really cool though

**Comment by LyncsCwtsh** [comment]
I pushed an update with better pathing today, so if Forge is grabbing version 1.0.1 already, it should work. If there's still issues, please let me know and I'll figure something out

**Comment by Bryn1701** [comment]
I no longer get errors, but saying that I no longer get the option for Nice more dice in DSN module. 
https://gyazo.com/244982103385d5083f89ed06f89e1d3d

I am on version 1.0.1

**Comment by LyncsCwtsh** [comment]
Alright, hopefully third time's the charm. Sorry, for the back and forth, I currently don't have a cloud hosted instance to test fixes for those cases

**Comment by Bryn1701** [comment]
Works now, but there are still some issues.
Celtic Lynx doesn't seem to work. It doesn't change the theme when you select it.
Maze is missing the D4 texture, as is flame stalker.
https://gyazo.com/21deac486bcf4fcf5a33af2faeda0ddf
https://gyazo.com/3eefe7fd144ad33c6f7f8b096e3ee68e

**Comment by LyncsCwtsh** [comment]
The d4 textures are there, they are sadly limited (e.g. I can only change the 'number side', not the whole die side).
For the lynx set, is the dice colour maybe set to black?

**Comment by LyncsCwtsh** [comment]
...it was a sneaky upper case B in the lynx set. Very sorry about that - fixed
