### ISSUE TITLE
Idea: let us add symbols to certain numbers

### ISSUE THREAD

**Issue by Zamino** [LyncsCwtsh/fvtt-module-nice-more-dice#7]
Hi there,
I like you module and I would love to see more possibilities to edit dices.

Do you think it there could be a way to edit what I can see on every number of a dice? We play a pen and paper which uses special d6 dices. On 5, 6 and 1 are a special symbols. The numbers 2,3 & 4 are empty. It would help us a lot not to see these numbers and add symbols to 1, 5 and 6.

**Comment by LyncsCwtsh** [comment]
My coding knowledge is sadly very limited and allowing users to change specific sides of a die without them having to code (or lose progress when updating Nice more Dice) is above my level.

However, depending on how special the design of the needed sides is, I could create dice faces that work with that.
What system are you using? I’ll check it out and see what I can do.
